name: Production
on:
  workflow_dispatch:

jobs:
  qa-job:
    runs-on: self-hosted
    environment: Production
    steps:
      - name: Echo description
        run: |
          echo ${{ vars.ENV_DESCRIPTION }}
